### ISSUE TITLE
Update node-gyp

### ISSUE THREAD

**Issue by eturino** [Widdershin/mmap-io#4]
Currently, we have `"node-gyp": "^3.8.0",` which is obsolete. It uses python2 inside, among other things, which is EOL. The team recommended to upgrade to latest node-gyp for the cases when it is needed.
I am using an apple M1 and sometimes when the pre-built versions in node-pre-gyp are not found, it fails when trying to use node-gyp because it uses such an old version of it.

Would it be possible to upgrade to latest node-gyp? Or at least to one of the python3 ones (v6 or later)

**Comment by eturino** [comment]
@Widdershin pinging as described in the README. Since it is a fork, I pinged you instead of ozra.

**Comment by Widdershin** [comment]
I’m in favour of updating node-gyp, would you be able to make a pull
request?

**Comment by eturino** [comment]
I would, but I have no idea how to test it, tbh. I have never done anything with gyp or C for that matter. I tried running `yarn test` from master and I get the following

```
node:assert:400
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Shit happened while reading from buffer
    at Object.<anonymous> (/Users/eturino/dev/temp/mmap-io/dist/test.js:50:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
error Command failed with exit code 1.
```

I assume that I am not preparing something right, and not that master is broken :/

**Comment by eturino** [comment]
I can make a blind PR and trust that the CI would do the job XD

**Comment by eturino** [comment]
the upgrade to 9.x fails on some nodes, since node-gyp requires 12.x or greater.
@Widdershin What's the minimum node version that should be supported?

**Comment by eturino** [comment]
@Widdershin could you confirm which node versions should be supported?

**Comment by Widdershin** [comment]
12.x to 18.x would be ideal. I’ll be looking into this soon now that 18.x
is out so no worries if you want me to handle it.

**Comment by eturino** [comment]
The PR https://github.com/Widdershin/mmap-io/pull/5 includes the changes to 18.x, but appveyor is not ready for it yet. @Widdershin

**Comment by Widdershin** [comment]
Thanks a ton! I’ll get this merged and released this week, don’t worry
about AppVeyor, I’ll replace it with GitHub Actions :)

**Comment by Widdershin** [comment]
It’s fine if you just target Node 12.x and onwards :)
